site_name: maSMP
site_url: https://zbmed-semtec.github.io/maSMP/
nav:
    - 'index.md'
    - 'maSMP_Schema.md'
    - Types:
      - 'Types/index.md'
      - 'Types/OutputManagementPlan.md'
      - 'Types/SoftwareManagementPlan.md'
      - 'Types/SoftwareRunAction.md'
      - 'Types/SoftwareTestAction.md'
    - Profiles:
      - 'Profiles/index.md'
      - 'Profiles/SoftwareManagementPlan.md'
      - 'Profiles/SoftwareSourceCode.md'
      - 'Profiles/SoftwareApplication.md'
      - 'Profiles/SoftwareRunAction.md'
      - 'Profiles/SoftwareTestAction.md'
    - 'tools.md'
    - 'about.md'
      
    
theme:
  name: material
  logo: maSMP_new_logo.png

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: light blue
      accent: teal 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: light blue
      accent: teal

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/zbmed-semtec/maSPMs
    

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html

plugins:
  - search


  

