site_name: maSMP - a project by ZB MED
site_url: https://zbmed-semtec.github.io/maSMP/
nav:
    - 'index.md'
    - 'maSMP_Schema.md'
    - Types:
      - 'Types/index.md'
      - 'Types/OutputManagementPlan.md'
      - 'Types/SoftwareManagementPlan.md'
      - 'Types/SoftwareRunAction.md'
      - 'Types/SoftwareTestAction.md'
    - Profiles:
      - 'Profiles/index.md'
      - 'Profiles/SoftwareManagementPlan.md'
      - 'Profiles/SoftwareSourceCode.md'
      - 'Profiles/SoftwareApplication.md'
      - 'Profiles/SoftwareRunAction.md'
      - 'Profiles/SoftwareTestAction.md'
    - 'tools.md'
    - 'about.md'
      
    
theme:
  name: material
  logo: maSMP_new_logo.png

  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: amber 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: blue
      accent: amber

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/zbmed-semtec/maSPMs
    

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - md_in_html

plugins:
  - search

copyright: >
  <div style="font-size:large; color:orange">
  <a href="https://www.zbmed.de/en/" target="_blank">ZB MED</a> | 
  <a href="https://www.zbmed.de/en/legal-notice" target="_blank">Legal notice</a> | 
  <a href="https://www.zbmed.de/en/disclaimer" target="_blank">Disclaimer</a> | 
  <a href="https://www.zbmed.de/en/privacy-policy" target="_blank">Privacy policy</a>
  </div>  


  

